# Statically link the Visual C++ runtime on Windows.
# This eliminates the vcruntime140.dll / msvcp140.dll dependency,
# so the app runs on machines without Visual C++ Redistributable installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
